name: "OpenSSF Scorecard"
on:
  branch_protection_rule:
  schedule: [{cron: "0 4 * * 1"}]
  push: {branches: [main]}
permissions:
  security-events: write
  contents: read
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
